services:
  frontend:
    build: ./frontend
    container_name: simi-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      DB_HOST: 172.31.83.96
      DB_PORT: 5432
      DB_NAME: simi_erp
      DB_USER: simi_user
      DB_PASSWORD: simi_pass
